// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package generate

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyStatusEnum string

const (
	IdempotencyStatusEnumPROCESSING IdempotencyStatusEnum = "PROCESSING"
	IdempotencyStatusEnumCOMPLETED  IdempotencyStatusEnum = "COMPLETED"
)

func (e *IdempotencyStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdempotencyStatusEnum(s)
	case string:
		*e = IdempotencyStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for IdempotencyStatusEnum: %T", src)
	}
	return nil
}

type NullIdempotencyStatusEnum struct {
	IdempotencyStatusEnum IdempotencyStatusEnum `json:"idempotency_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if IdempotencyStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdempotencyStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.IdempotencyStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdempotencyStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdempotencyStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdempotencyStatusEnum), nil
}

func (e IdempotencyStatusEnum) Valid() bool {
	switch e {
	case IdempotencyStatusEnumPROCESSING,
		IdempotencyStatusEnumCOMPLETED:
		return true
	}
	return false
}

type InvoiceStateEnum string

const (
	InvoiceStateEnumDRAFT         InvoiceStateEnum = "DRAFT"
	InvoiceStateEnumOPEN          InvoiceStateEnum = "OPEN"
	InvoiceStateEnumPAID          InvoiceStateEnum = "PAID"
	InvoiceStateEnumVOID          InvoiceStateEnum = "VOID"
	InvoiceStateEnumUNCOLLECTIBLE InvoiceStateEnum = "UNCOLLECTIBLE"
)

func (e *InvoiceStateEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStateEnum(s)
	case string:
		*e = InvoiceStateEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStateEnum: %T", src)
	}
	return nil
}

type NullInvoiceStateEnum struct {
	InvoiceStateEnum InvoiceStateEnum `json:"invoice_state_enum"`
	Valid            bool             `json:"valid"` // Valid is true if InvoiceStateEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStateEnum) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStateEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStateEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStateEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStateEnum), nil
}

func (e InvoiceStateEnum) Valid() bool {
	switch e {
	case InvoiceStateEnumDRAFT,
		InvoiceStateEnumOPEN,
		InvoiceStateEnumPAID,
		InvoiceStateEnumVOID,
		InvoiceStateEnumUNCOLLECTIBLE:
		return true
	}
	return false
}

type PaymentStatusEnum string

const (
	PaymentStatusEnumPROCESSING PaymentStatusEnum = "PROCESSING"
	PaymentStatusEnumSUCCEEDED  PaymentStatusEnum = "SUCCEEDED"
	PaymentStatusEnumFAILED     PaymentStatusEnum = "FAILED"
	PaymentStatusEnumUNKNOWN    PaymentStatusEnum = "UNKNOWN"
)

func (e *PaymentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatusEnum(s)
	case string:
		*e = PaymentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatusEnum: %T", src)
	}
	return nil
}

type NullPaymentStatusEnum struct {
	PaymentStatusEnum PaymentStatusEnum `json:"payment_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatusEnum), nil
}

func (e PaymentStatusEnum) Valid() bool {
	switch e {
	case PaymentStatusEnumPROCESSING,
		PaymentStatusEnumSUCCEEDED,
		PaymentStatusEnumFAILED,
		PaymentStatusEnumUNKNOWN:
		return true
	}
	return false
}

type WebhookDeliveryStatusEnum string

const (
	WebhookDeliveryStatusEnumPENDING    WebhookDeliveryStatusEnum = "PENDING"
	WebhookDeliveryStatusEnumPROCESSING WebhookDeliveryStatusEnum = "PROCESSING"
	WebhookDeliveryStatusEnumDELIVERED  WebhookDeliveryStatusEnum = "DELIVERED"
	WebhookDeliveryStatusEnumEXHAUSTED  WebhookDeliveryStatusEnum = "EXHAUSTED"
)

func (e *WebhookDeliveryStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatusEnum(s)
	case string:
		*e = WebhookDeliveryStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatusEnum: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatusEnum struct {
	WebhookDeliveryStatusEnum WebhookDeliveryStatusEnum `json:"webhook_delivery_status_enum"`
	Valid                     bool                      `json:"valid"` // Valid is true if WebhookDeliveryStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatusEnum), nil
}

func (e WebhookDeliveryStatusEnum) Valid() bool {
	switch e {
	case WebhookDeliveryStatusEnumPENDING,
		WebhookDeliveryStatusEnumPROCESSING,
		WebhookDeliveryStatusEnumDELIVERED,
		WebhookDeliveryStatusEnumEXHAUSTED:
		return true
	}
	return false
}

type WebhookEventTypeEnum string

const (
	WebhookEventTypeEnumINVOICECREATED       WebhookEventTypeEnum = "INVOICE.CREATED"
	WebhookEventTypeEnumINVOICEPAID          WebhookEventTypeEnum = "INVOICE.PAID"
	WebhookEventTypeEnumINVOICEPAYMENTFAILED WebhookEventTypeEnum = "INVOICE.PAYMENT_FAILED"
)

func (e *WebhookEventTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookEventTypeEnum(s)
	case string:
		*e = WebhookEventTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookEventTypeEnum: %T", src)
	}
	return nil
}

type NullWebhookEventTypeEnum struct {
	WebhookEventTypeEnum WebhookEventTypeEnum `json:"webhook_event_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if WebhookEventTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookEventTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookEventTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookEventTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookEventTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookEventTypeEnum), nil
}

func (e WebhookEventTypeEnum) Valid() bool {
	switch e {
	case WebhookEventTypeEnumINVOICECREATED,
		WebhookEventTypeEnumINVOICEPAID,
		WebhookEventTypeEnumINVOICEPAYMENTFAILED:
		return true
	}
	return false
}

type ApiKey struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	KeyPrefix  string             `json:"key_prefix"`
	SecretHash string             `json:"secret_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Business struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKey struct {
	ID             int64                 `json:"id"`
	BusinessID     int64                 `json:"business_id"`
	IdempotencyKey string                `json:"idempotency_key"`
	RequestHash    string                `json:"request_hash"`
	Status         IdempotencyStatusEnum `json:"status"`
	ResponseStatus pgtype.Int4           `json:"response_status"`
	ResponseBody   []byte                `json:"response_body"`
	CreatedAt      pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `json:"updated_at"`
}

type Invoice struct {
	ID               int64              `json:"id"`
	BusinessID       int64              `json:"business_id"`
	CustomerID       int64              `json:"customer_id"`
	TotalAmountCents int64              `json:"total_amount_cents"`
	Currency         string             `json:"currency"`
	State            InvoiceStateEnum   `json:"state"`
	DueDate          pgtype.Date        `json:"due_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceItem struct {
	ID              int64              `json:"id"`
	InvoiceID       int64              `json:"invoice_id"`
	Description     string             `json:"description"`
	Quantity        int32              `json:"quantity"`
	UnitAmountCents int64              `json:"unit_amount_cents"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PaymentAttempt struct {
	ID               int64              `json:"id"`
	InvoiceID        int64              `json:"invoice_id"`
	IdempotencyKeyID int64              `json:"idempotency_key_id"`
	Status           PaymentStatusEnum  `json:"status"`
	PspRequestID     int64              `json:"psp_request_id"`
	PspRef           pgtype.Text        `json:"psp_ref"`
	FailureCode      pgtype.Text        `json:"failure_code"`
	FailureReason    pgtype.Text        `json:"failure_reason"`
	PspRequestedAt   pgtype.Timestamptz `json:"psp_requested_at"`
	PspRespondedAt   pgtype.Timestamptz `json:"psp_responded_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID                int64                     `json:"id"`
	WebhookEndpointID int64                     `json:"webhook_endpoint_id"`
	InvoiceID         int64                     `json:"invoice_id"`
	EventType         WebhookEventTypeEnum      `json:"event_type"`
	Payload           []byte                    `json:"payload"`
	Status            WebhookDeliveryStatusEnum `json:"status"`
	AttemptCount      int32                     `json:"attempt_count"`
	NextAttemptAt     pgtype.Timestamptz        `json:"next_attempt_at"`
	LastError         pgtype.Text               `json:"last_error"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	DeliveredAt       pgtype.Timestamptz        `json:"delivered_at"`
}

type WebhookEndpoint struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Url        string             `json:"url"`
	Secret     string             `json:"secret"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
