// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package generate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET status = 'COMPLETED', response_status = $2, response_body = $3, updated_at = NOW()
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, business_id, idempotency_key, request_hash, status, response_status, response_body, created_at, updated_at
`

type CompleteIdempotencyKeyParams struct {
	ID             int64       `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey, arg.ID, arg.ResponseStatus, arg.ResponseBody)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    id, business_id, idempotency_key, request_hash, status,
    response_status, response_body, created_at, updated_at
) VALUES ($1, $2, $3, $4, 'PROCESSING', NULL, NULL, NOW(), NOW())
RETURNING id, business_id, idempotency_key, request_hash, status, response_status, response_body, created_at, updated_at
`

type CreateIdempotencyKeyParams struct {
	ID             int64  `json:"id"`
	BusinessID     int64  `json:"business_id"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    string `json:"request_hash"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.ID,
		arg.BusinessID,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    id, invoice_id, idempotency_key_id, status, psp_request_id,
    psp_requested_at, created_at, updated_at
) VALUES ($1, $2, $3, 'PROCESSING', $4, NOW(), NOW(), NOW())
RETURNING id, invoice_id, idempotency_key_id, status, psp_request_id, psp_ref, failure_code, failure_reason, psp_requested_at, psp_responded_at, created_at, updated_at
`

type CreatePaymentAttemptParams struct {
	ID               int64 `json:"id"`
	InvoiceID        int64 `json:"invoice_id"`
	IdempotencyKeyID int64 `json:"idempotency_key_id"`
	PspRequestID     int64 `json:"psp_request_id"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.ID,
		arg.InvoiceID,
		arg.IdempotencyKeyID,
		arg.PspRequestID,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.IdempotencyKeyID,
		&i.Status,
		&i.PspRequestID,
		&i.PspRef,
		&i.FailureCode,
		&i.FailureReason,
		&i.PspRequestedAt,
		&i.PspRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, business_id, idempotency_key, request_hash, status, response_status, response_body, created_at, updated_at FROM idempotency_keys
WHERE business_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	BusinessID     int64  `json:"business_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.BusinessID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceForPayment = `-- name: GetInvoiceForPayment :one
SELECT id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at FROM invoices
WHERE id = $1 AND business_id = $2
FOR UPDATE
`

type GetInvoiceForPaymentParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetInvoiceForPayment(ctx context.Context, arg GetInvoiceForPaymentParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceForPayment, arg.ID, arg.BusinessID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalAmountCents,
		&i.Currency,
		&i.State,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKeyID = `-- name: GetPaymentAttemptByIdempotencyKeyID :one
SELECT id, invoice_id, idempotency_key_id, status, psp_request_id, psp_ref, failure_code, failure_reason, psp_requested_at, psp_responded_at, created_at, updated_at FROM payment_attempts WHERE idempotency_key_id = $1
`

func (q *Queries) GetPaymentAttemptByIdempotencyKeyID(ctx context.Context, idempotencyKeyID int64) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKeyID, idempotencyKeyID)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.IdempotencyKeyID,
		&i.Status,
		&i.PspRequestID,
		&i.PspRef,
		&i.FailureCode,
		&i.FailureReason,
		&i.PspRequestedAt,
		&i.PspRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :one
UPDATE invoices SET state = 'PAID', updated_at = NOW()
WHERE id = $1 AND business_id = $2 AND state = 'OPEN'
RETURNING id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at
`

type MarkInvoicePaidParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, markInvoicePaid, arg.ID, arg.BusinessID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalAmountCents,
		&i.Currency,
		&i.State,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentAttemptFailed = `-- name: MarkPaymentAttemptFailed :one
UPDATE payment_attempts
SET status = 'FAILED', failure_code = $2, failure_reason = $3,
    psp_responded_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, invoice_id, idempotency_key_id, status, psp_request_id, psp_ref, failure_code, failure_reason, psp_requested_at, psp_responded_at, created_at, updated_at
`

type MarkPaymentAttemptFailedParams struct {
	ID            int64       `json:"id"`
	FailureCode   pgtype.Text `json:"failure_code"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) MarkPaymentAttemptFailed(ctx context.Context, arg MarkPaymentAttemptFailedParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, markPaymentAttemptFailed, arg.ID, arg.FailureCode, arg.FailureReason)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.IdempotencyKeyID,
		&i.Status,
		&i.PspRequestID,
		&i.PspRef,
		&i.FailureCode,
		&i.FailureReason,
		&i.PspRequestedAt,
		&i.PspRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentAttemptSucceeded = `-- name: MarkPaymentAttemptSucceeded :one
UPDATE payment_attempts
SET status = 'SUCCEEDED', psp_ref = $2, psp_responded_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, invoice_id, idempotency_key_id, status, psp_request_id, psp_ref, failure_code, failure_reason, psp_requested_at, psp_responded_at, created_at, updated_at
`

type MarkPaymentAttemptSucceededParams struct {
	ID     int64       `json:"id"`
	PspRef pgtype.Text `json:"psp_ref"`
}

func (q *Queries) MarkPaymentAttemptSucceeded(ctx context.Context, arg MarkPaymentAttemptSucceededParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, markPaymentAttemptSucceeded, arg.ID, arg.PspRef)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.IdempotencyKeyID,
		&i.Status,
		&i.PspRequestID,
		&i.PspRef,
		&i.FailureCode,
		&i.FailureReason,
		&i.PspRequestedAt,
		&i.PspRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentAttemptUnknown = `-- name: MarkPaymentAttemptUnknown :one
UPDATE payment_attempts
SET status = 'UNKNOWN', failure_reason = $2, updated_at = NOW()
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, invoice_id, idempotency_key_id, status, psp_request_id, psp_ref, failure_code, failure_reason, psp_requested_at, psp_responded_at, created_at, updated_at
`

type MarkPaymentAttemptUnknownParams struct {
	ID            int64       `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) MarkPaymentAttemptUnknown(ctx context.Context, arg MarkPaymentAttemptUnknownParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, markPaymentAttemptUnknown, arg.ID, arg.FailureReason)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.IdempotencyKeyID,
		&i.Status,
		&i.PspRequestID,
		&i.PspRef,
		&i.FailureCode,
		&i.FailureReason,
		&i.PspRequestedAt,
		&i.PspRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
