// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package generate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (id, business_id, key_prefix, secret_hash, created_at, revoked_at)
VALUES ($1, $2, $3, $4, NOW(), NULL) RETURNING id, business_id, key_prefix, secret_hash, created_at, revoked_at
`

type CreateApiKeyParams struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	KeyPrefix  string `json:"key_prefix"`
	SecretHash string `json:"secret_hash"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.BusinessID,
		arg.KeyPrefix,
		arg.SecretHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (id, name, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW()) RETURNING id, name, created_at, updated_at
`

type CreateBusinessParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.ID, arg.Name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, business_id, name, email, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW()) RETURNING id, business_id, name, email, created_at, updated_at
`

type CreateCustomerParams struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.BusinessID,
		arg.Name,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW()) RETURNING id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID               int64            `json:"id"`
	BusinessID       int64            `json:"business_id"`
	CustomerID       int64            `json:"customer_id"`
	TotalAmountCents int64            `json:"total_amount_cents"`
	Currency         string           `json:"currency"`
	State            InvoiceStateEnum `json:"state"`
	DueDate          pgtype.Date      `json:"due_date"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.BusinessID,
		arg.CustomerID,
		arg.TotalAmountCents,
		arg.Currency,
		arg.State,
		arg.DueDate,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalAmountCents,
		&i.Currency,
		&i.State,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (id, invoice_id, description, quantity, unit_amount_cents, created_at)
VALUES ($1, $2, $3, $4, $5, NOW()) RETURNING id, invoice_id, description, quantity, unit_amount_cents, created_at
`

type CreateInvoiceItemParams struct {
	ID              int64  `json:"id"`
	InvoiceID       int64  `json:"invoice_id"`
	Description     string `json:"description"`
	Quantity        int32  `json:"quantity"`
	UnitAmountCents int64  `json:"unit_amount_cents"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitAmountCents,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitAmountCents,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByPrefix = `-- name: GetApiKeyByPrefix :one
SELECT id, business_id, key_prefix, secret_hash, created_at, revoked_at FROM api_keys WHERE key_prefix = $1
`

func (q *Queries) GetApiKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, name, created_at, updated_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id int64) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByName = `-- name: GetBusinessByName :one
SELECT id, name, created_at, updated_at FROM businesses WHERE name = $1
`

func (q *Queries) GetBusinessByName(ctx context.Context, name string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByName, name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, business_id, name, email, created_at, updated_at FROM customers WHERE id = $1 AND business_id = $2
`

type GetCustomerByIDParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.BusinessID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at FROM invoices WHERE id = $1 AND business_id = $2
`

type GetInvoiceByIDParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.BusinessID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalAmountCents,
		&i.Currency,
		&i.State,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeysByBusinessID = `-- name: ListApiKeysByBusinessID :many
SELECT id, business_id, key_prefix, secret_hash, created_at, revoked_at FROM api_keys WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByBusinessID(ctx context.Context, businessID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.KeyPrefix,
			&i.SecretHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByBusinessID = `-- name: ListCustomersByBusinessID :many
SELECT id, business_id, name, email, created_at, updated_at FROM customers WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCustomersByBusinessID(ctx context.Context, businessID int64) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceItemsByInvoiceID = `-- name: ListInvoiceItemsByInvoiceID :many
SELECT id, invoice_id, description, quantity, unit_amount_cents, created_at FROM invoice_items WHERE invoice_id = $1 ORDER BY id ASC
`

func (q *Queries) ListInvoiceItemsByInvoiceID(ctx context.Context, invoiceID int64) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItemsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitAmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceItemsByInvoiceIDs = `-- name: ListInvoiceItemsByInvoiceIDs :many
SELECT id, invoice_id, description, quantity, unit_amount_cents, created_at FROM invoice_items WHERE invoice_id = ANY($1::bigint[]) ORDER BY id ASC
`

func (q *Queries) ListInvoiceItemsByInvoiceIDs(ctx context.Context, dollar_1 []int64) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItemsByInvoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitAmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByBusinessID = `-- name: ListInvoicesByBusinessID :many
SELECT id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at FROM invoices WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByBusinessID(ctx context.Context, businessID int64) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CustomerID,
			&i.TotalAmountCents,
			&i.Currency,
			&i.State,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceState = `-- name: UpdateInvoiceState :one
UPDATE invoices SET state = $3, updated_at = NOW()
WHERE id = $1 AND business_id = $2 RETURNING id, business_id, customer_id, total_amount_cents, currency, state, due_date, created_at, updated_at
`

type UpdateInvoiceStateParams struct {
	ID         int64            `json:"id"`
	BusinessID int64            `json:"business_id"`
	State      InvoiceStateEnum `json:"state"`
}

func (q *Queries) UpdateInvoiceState(ctx context.Context, arg UpdateInvoiceStateParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceState, arg.ID, arg.BusinessID, arg.State)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalAmountCents,
		&i.Currency,
		&i.State,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
