// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package generate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
WITH due AS (
    SELECT wd.id
    FROM webhook_deliveries wd
    WHERE (wd.status = 'PENDING' AND wd.next_attempt_at <= NOW())
       OR (wd.status = 'PROCESSING' AND wd.next_attempt_at <= NOW())
    ORDER BY wd.next_attempt_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE webhook_deliveries wd
SET status = 'PROCESSING',
    next_attempt_at = $2,
    attempt_count = wd.attempt_count + 1
FROM due, webhook_endpoints we
WHERE wd.id = due.id AND wd.webhook_endpoint_id = we.id
RETURNING wd.id, wd.webhook_endpoint_id, wd.invoice_id, wd.event_type, wd.payload, wd.status, wd.attempt_count, wd.next_attempt_at, wd.last_error, wd.created_at, wd.delivered_at, we.url AS endpoint_url, we.secret AS endpoint_secret
`

type ClaimDueWebhookDeliveriesParams struct {
	Limit         int32              `json:"limit"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

type ClaimDueWebhookDeliveriesRow struct {
	ID                int64                     `json:"id"`
	WebhookEndpointID int64                     `json:"webhook_endpoint_id"`
	InvoiceID         int64                     `json:"invoice_id"`
	EventType         WebhookEventTypeEnum      `json:"event_type"`
	Payload           []byte                    `json:"payload"`
	Status            WebhookDeliveryStatusEnum `json:"status"`
	AttemptCount      int32                     `json:"attempt_count"`
	NextAttemptAt     pgtype.Timestamptz        `json:"next_attempt_at"`
	LastError         pgtype.Text               `json:"last_error"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	DeliveredAt       pgtype.Timestamptz        `json:"delivered_at"`
	EndpointUrl       string                    `json:"endpoint_url"`
	EndpointSecret    string                    `json:"endpoint_secret"`
}

func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, arg ClaimDueWebhookDeliveriesParams) ([]ClaimDueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDueWebhookDeliveries, arg.Limit, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimDueWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookEndpointID,
			&i.InvoiceID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.EndpointUrl,
			&i.EndpointSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id, webhook_endpoint_id, invoice_id, event_type, payload,
    status, attempt_count, next_attempt_at, last_error, created_at, delivered_at
) VALUES (
    $1, $2, $3, $4, $5,
    'PENDING', 0, NOW(), NULL, NOW(), NULL
) RETURNING id, webhook_endpoint_id, invoice_id, event_type, payload, status, attempt_count, next_attempt_at, last_error, created_at, delivered_at
`

type CreateWebhookDeliveryParams struct {
	ID                int64                `json:"id"`
	WebhookEndpointID int64                `json:"webhook_endpoint_id"`
	InvoiceID         int64                `json:"invoice_id"`
	EventType         WebhookEventTypeEnum `json:"event_type"`
	Payload           []byte               `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.WebhookEndpointID,
		arg.InvoiceID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookEndpointID,
		&i.InvoiceID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (id, business_id, url, secret, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, true, NOW(), NOW())
RETURNING id, business_id, url, secret, is_active, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Url        string `json:"url"`
	Secret     string `json:"secret"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.BusinessID,
		arg.Url,
		arg.Secret,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, business_id, url, secret, is_active, created_at, updated_at FROM webhook_endpoints
WHERE id = $1 AND business_id = $2
`

type GetWebhookEndpointByIDParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, arg GetWebhookEndpointByIDParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, arg.ID, arg.BusinessID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhookEndpointsByBusinessID = `-- name: ListActiveWebhookEndpointsByBusinessID :many
SELECT id, business_id, url, secret, is_active, created_at, updated_at FROM webhook_endpoints
WHERE business_id = $1 AND is_active = true
ORDER BY id ASC
`

func (q *Queries) ListActiveWebhookEndpointsByBusinessID(ctx context.Context, businessID int64) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookEndpointsByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsByBusinessID = `-- name: ListWebhookEndpointsByBusinessID :many
SELECT id, business_id, url, secret, is_active, created_at, updated_at FROM webhook_endpoints
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpointsByBusinessID(ctx context.Context, businessID int64) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :one
UPDATE webhook_deliveries
SET status = 'DELIVERED',
    delivered_at = NOW(),
    last_error = NULL
WHERE id = $1
RETURNING id, webhook_endpoint_id, invoice_id, event_type, payload, status, attempt_count, next_attempt_at, last_error, created_at, delivered_at
`

func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, id int64) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryDelivered, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookEndpointID,
		&i.InvoiceID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const markWebhookDeliveryExhausted = `-- name: MarkWebhookDeliveryExhausted :one
UPDATE webhook_deliveries
SET status = 'EXHAUSTED',
    last_error = $2
WHERE id = $1
RETURNING id, webhook_endpoint_id, invoice_id, event_type, payload, status, attempt_count, next_attempt_at, last_error, created_at, delivered_at
`

type MarkWebhookDeliveryExhaustedParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkWebhookDeliveryExhausted(ctx context.Context, arg MarkWebhookDeliveryExhaustedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryExhausted, arg.ID, arg.LastError)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookEndpointID,
		&i.InvoiceID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const markWebhookDeliveryRetry = `-- name: MarkWebhookDeliveryRetry :one
UPDATE webhook_deliveries
SET status = 'PENDING',
    next_attempt_at = $2,
    last_error = $3
WHERE id = $1
RETURNING id, webhook_endpoint_id, invoice_id, event_type, payload, status, attempt_count, next_attempt_at, last_error, created_at, delivered_at
`

type MarkWebhookDeliveryRetryParams struct {
	ID            int64              `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkWebhookDeliveryRetry(ctx context.Context, arg MarkWebhookDeliveryRetryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookEndpointID,
		&i.InvoiceID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
